import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import Aside from "@/components/Aside";
import Aside from "@/components/aside/Aside";
import "./globals.css";
import LabSystemProvider from "@/context/LabContext";
import OnlineStatus from "@/utils/OnlineStatus";
import { FaHospitalAlt } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lab Patient System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-dvh w-full flex bg-sky-200`}
        // style={{
        //   backgroundImage: "url('/images/image4.jpg')",
        //   backgroundSize: "cover",
        //   backgroundPosition: "center",
        // }}
      >
        <LabSystemProvider>
          <OnlineStatus>
            <div className="h-full w-full relative overflow-hidden">
              {" "}
              <div className="bg-green-500 w-full h-12 absolute flex justify-center items-center hidden">
                <p className="text-black text-xl">In process</p>
              </div>
              <div className="h-full flex w-full text-black min-w-[480px]">
                <Aside></Aside>
                <div className="relative w-full h-full">
                  <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-3/4 2xl:-translate-y-12/14 w-[200%] h-[250%] 2xl:h-[400%] bg-sky-900/80 rounded-full -z-10"></div>

                  <div className="text-black h-full overflow-y-auto flex-col w-full flex justify-center items-end  overflow-hidden  relative">
                    <div className="flex items-center justify-center w-full px-6 absolute top-16">
                      {/* Línea izquierda */}
                      <span className="flex-grow border-t border-2 border-sky-100/70"></span>

                      {/* Icono con círculo */}
                      <div className="p-4 ">
                        <FaHospitalAlt className="w-10 h-10 text-sky-100/70" />
                      </div>

                      {/* Línea derecha */}
                      <span className="flex-grow border-t border-2 border-sky-100/70"></span>
                    </div>
                    <div className="mx-auto h-full overflow-hidden  w-2/3">
                      {children}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </OnlineStatus>
        </LabSystemProvider>
      </body>
    </html>
  );
}
