import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import Aside from "@/components/Aside";
import Aside from "@/components/aside/Aside";
import "./globals.css";
import LabSystemProvider from "@/context/LabContext";
import OnlineStatus from "@/utils/OnlineStatus";
import { FaHospitalAlt } from "react-icons/fa";
import { Toast } from "@/components/atomics/Toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lab Patient System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-dvh w-full flex bg-sky-200`}
        // style={{
        //   backgroundImage: "url('/images/image4.jpg')",
        //   backgroundSize: "cover",
        //   backgroundPosition: "center",
        // }}
      >
        <LabSystemProvider>
          <OnlineStatus>
            <div className="h-full w-full relative overflow-hidden flex">
              <Toast
                message="Paciente agregado con éxito!"
                color="green"
                visible={false}
              ></Toast>
              {/* process */}
              <div className="bg-green-500 w-full h-12 absolute flex justify-center items-center hidden">
                <p className="text-black text-xl">In process</p>
              </div>
              <div className="h-full flex w-full text-black min-w-[480px]">
                {" "}
                <Aside></Aside>
                <div className="relative flex-1 h-full ">
                  <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-3/4 2xl:-translate-y-12/14 w-[200%] h-[250%] 2xl:h-[400%] bg-sky-900/80 rounded-full -z-10"></div>

                  <div className="text-black  h-full overflow-y-auto flex-col w-full flex justify-evenly items-end  overflow-hidden  relative ">
                    {/* banner */}
                    <div className="xl:absolute flex items-center justify-center w-full px-6 top-0  xl:top-0 2xl:top-20">
                      <span className="flex-grow border-t border-2  border-sky-100/70"></span>
                      <div className="p-4 ">
                        <FaHospitalAlt className="w-10 h-10  text-sky-100/70" />
                      </div>
                      <span className="flex-grow border-t border-2  border-sky-100/70"></span>
                    </div>
                    <div className="mx-auto overflow-hidden w-full  2xl:w-4/5 h-full ">
                      {/* children */}
                      {children}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </OnlineStatus>
        </LabSystemProvider>
      </body>
    </html>
  );
}
